---
title: "[성과분석] 더제이수"
author: "hjlee"
date: '2019-10-29'
slug: report-thejsoo-20191029
categories: []
tags: ["성과분석", "기획전", "더제이수"]
output:
  html_document:
    toc: true
    highlight: tango
    theme: flatly
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(highcharter)
library(reshape2)
#devtools::install_github("timelyportfolio/d3vennR")
library("d3vennR")
library(DT)

# for using Korean
theme_set(theme_gray(base_family='NanumGothic'))

# load data

data.path = "./content/post/report-thejsoo-20191029"

ad.page = read.csv(file.path(data.path, "모아보기탭 방문자수.csv"), stringsAsFactors = F, header = T)
ad.page$date_no = as.Date(ad.page$date_no)

event.page = read.csv(file.path(data.path, "더제이수 페이지 pv_uv.csv"), stringsAsFactors = F, header = T)
event.page$date_no = as.Date(event.page$date_no)

event.page_vs = read.csv(file.path(data.path, "트렌드어패럴 vs 메리어라운드 vs 엔비룩 vs 더제이수.csv"), stringsAsFactors = F, header = T)
event.page_vs$date_no = as.Date(event.page_vs$date_no)



shop_dailies_thejsoo = read.csv(file.path(data.path, "더제이수 쇼핑몰 페이지 PV_UV(경쟁사 포함).csv"), stringsAsFactors = F, header = T)
shop_dailies_thejsoo$date_simple = as.Date(shop_dailies_thejsoo$date_simple)

orders.thejsoo = read.csv(file.path(data.path, "더제이수 쇼핑몰 주문액(경쟁사 포함).csv"), stringsAsFactors = F, header = T)
orders.thejsoo$date_paid_simple = as.Date(orders.thejsoo$date_paid_simple)


#### 일자 설정 ####### 

start_date = "2019-10-26"
end_date = "2019-10-28"


```

# 주요요약 

----------------------------------------------------------------------------------------

**1. 트래픽 **

  - 더제이수의 경우 타 프로모션과 다르게 진행경과일수가 진행됨에 따라 pv 및 uv수치가 보합세 혹은 증가세를 나타냄.
  - 5회차에 진행했던 엔비룩과 비교하였을 시, 트래픽 측면패턴에서 증가패턴을 보임.
  
**2. 결제 **

  - 기간내(26일 ~ 28일) 발생한 매출액은 3일차에 가장 높게 발생함.(3일차 : 약 791만원)
  - 다만, 2일차엔 Z결제 매출 비율이 높은 반면(2일차 z결제매출 비율 : 약 65.8%), 3일차에는 자사몰 결제 매출비율이 높게 역전되어 발생함.(3일차 z결제매출 비율 : 약 54%)
  - 10월 한달간 살펴봤을 경우 매출이 가장 높았던 시점(10월 7일:약 550만원)대비 약 50% 매출 증가 발생.


**3. 기타**

  - 기획전 기간내 즐겨찾기 수 약 2배 증가, 찜 수 약 3배 증가함.


----------------------------------------------------------------------------------------




# 전체성과

```{r, echo=FALSE}
#cat("원본 데이터: https://bit.ly/2LUR3r8")


start_date = "2019-10-26"
end_date = "2019-10-28"

result_total = event.page %>%
  summarise(uv = sum(uv),
            pv = sum(pv))

result_amount_type = orders.thejsoo %>%
  filter(date_paid_simple >= start_date & date_paid_simple <= end_date) %>%
  filter(shop_id == 2003) %>%
  group_by(type) %>%
  summarise(total_order_num = sum(order_num),
            total_order_amount = sum(order_amount))

result_amount_total = orders.thejsoo %>%
  filter(date_paid_simple >= start_date & date_paid_simple <= end_date) %>%
  filter(shop_id == 2003) %>%
  summarise(total_order_num = sum(order_num),
            total_order_amount = sum(order_amount))

cat(sprintf("기간: %s ~ %s (3일간)
총 주문수: %s 건
- Z결제: %s 건
- 자사몰결제: %s 건
총 주문액: %s 원
- Z결제: %s 원
- 자사몰결제: %s 원
이벤트페이지 클릭수: %s 회
이벤트페이지 방문자수: %s 명",start_date
                                ,end_date
                                ,prettyNum(result_amount_total$total_order_num,big.mark=",")
                                ,prettyNum(result_amount_type[which(result_amount_type$type == 'zpay'),2],big.mark=",")
                                ,prettyNum(result_amount_type[which(result_amount_type$type == 'meta'),2],big.mark=",")
                                ,prettyNum(result_amount_total$total_order_amount,big.mark=",")
                                ,prettyNum(result_amount_type[which(result_amount_type$type == 'zpay'),3],big.mark=",")
                                ,prettyNum(result_amount_type[which(result_amount_type$type == 'meta'),3],big.mark=",")
                                ,prettyNum(result_total$pv,big.mark=",")
                                ,prettyNum(result_total$uv,big.mark=",")))
```

# 푸시 오픈율

```{r, echo=FALSE}
cat("10/26 ~ 10/28 오픈
캠페인 오픈율: 0.68% (4463 / 660590)
푸시 오픈율: 1.7% (3129 / 183733)
알림센터 오픈율: 0.23% (1370 / 604743)
------------------------------------------
iOS 오픈율: 0.64% (3114 / 488589)
iOS 푸시 오픈율: 1.59% (1883 / 118394)
iOS 알림센터 오픈율: 0.28% (1262 / 458094)
And 오픈율: 0.78% (1349 / 172001)
And 푸시 오픈율: 1.91% (1246 / 65339)
")

```

## 모아보기탭{.tabset .tabset-fade .tabset-pills}

### 일자별 모아보기 탭 PV

```{r, echo=FALSE,warning=FALSE}
dat = ad.page

dat = melt(data=dat, id=c("date_no"))


hcoptslang <- getOption("highcharter.lang")
  hcoptslang$thousandsSep <- ","
  options(highcharter.lang = hcoptslang)
  
  hchart(dat, "line", hcaes(x=date_no,y=value,group = variable,colour = variable))%>%
    hc_yAxis(title = list(text = "PV")) %>%  ## y축 labeling 
    hc_xAxis(title = list(text = "일자")) %>%  ## x축 labeling
    hc_plotOptions(series = list(marker = list(enabled = TRUE,symbol = "circle"))) %>%
    hc_tooltip(crosshairs = TRUE,
               shared = TRUE,
               borderColor = "black",
               pointFormat = '<span style="color:{point.color}"> \u25CF </span> {point.variable}: {point.value:,.0f} <br>') %>%  ## tooltip 설정
    hc_title(text = "<b> 일자별 모아보기 탭_PV</b>",
             margin = 20, align = "center",
             style = list(color = "#000000", useHTML = TRUE)) %>%
    hc_xAxis(plotBands = list(
      list(from =  datetime_to_timestamp(as.Date(start_date))
           , to = datetime_to_timestamp(as.Date(end_date))
           , color = "rgba(255,60,0, 0.4)")
    ))
  
  
```

### 더제이수 pv/uv

```{r, echo=FALSE}


dat = event.page

dat = dat %>% group_by(date_no) %>% summarise(pv = sum(pv),uv=sum(uv))

dat = melt(data=dat, id=c("date_no"))

hcoptslang <- getOption("highcharter.lang")
  hcoptslang$thousandsSep <- ","
  options(highcharter.lang = hcoptslang)
  
hchart(dat, "line", hcaes(x=date_no,y=value,group = variable,colour = variable))%>%
    hc_yAxis(title = list(text = "PV")) %>%  ## y축 labeling 
    hc_xAxis(title = list(text = "일자")) %>%  ## x축 labeling
    hc_plotOptions(series = list(marker = list(enabled = TRUE,symbol = "circle"))) %>%
    hc_tooltip(crosshairs = TRUE,
               shared = TRUE,
               borderColor = "black",
               pointFormat = '<span style="color:{point.color}"> \u25CF </span> {point.variable}: {point.value:,.0f} <br>') %>%  ## tooltip 설정
    hc_title(text = "<b> 더제이수 pv_uv</b>",
             margin = 20, align = "center",
             style = list(color = "#000000", useHTML = TRUE))
  

```

### 프로모션별 pv 비교

```{r, echo=FALSE}


dat = event.page_vs

dat = dat %>% 
      group_by(rn,promo_type) %>% 
      summarise(pv = sum(pv),uv=sum(uv))

dat = melt(data=dat, id=c("promo_type","rn")) %>% filter(variable == 'pv')


hcoptslang <- getOption("highcharter.lang")
  hcoptslang$thousandsSep <- ","
  options(highcharter.lang = hcoptslang)
  
hchart(dat, "line", hcaes(x=paste0(rn,"일차"),y=value,group = promo_type,colour = promo_type))%>%
    hc_yAxis(title = list(text = "PV")) %>%  ## y축 labeling 
    hc_xAxis(title = list(text = "일자")) %>%  ## x축 labeling
    hc_plotOptions(series = list(marker = list(enabled = TRUE,symbol = "circle"))) %>%
    hc_tooltip(crosshairs = TRUE,
               shared = TRUE,
               borderColor = "black",
               pointFormat = '<span style="color:{point.color}"> \u25CF </span> {point.promo_type}: {point.value:,.0f} <br>') %>%  ## tooltip 설정
    hc_title(text = "<b> 프로모션 pv비교</b>",
             margin = 20, align = "center",
             style = list(color = "#000000", useHTML = TRUE))
  

```

### 프로모션별 uv 비교

```{r, echo=FALSE}

dat = event.page_vs

dat = dat %>% 
      group_by(rn,promo_type) %>% 
      summarise(pv = sum(pv),uv=sum(uv))

dat = melt(data=dat, id=c("promo_type","rn")) %>% filter(variable == 'uv')


hcoptslang <- getOption("highcharter.lang")
  hcoptslang$thousandsSep <- ","
  options(highcharter.lang = hcoptslang)
  
hchart(dat, "line", hcaes(x=paste0(rn,"일차"),y=value,group = promo_type,colour = promo_type))%>%
    hc_yAxis(title = list(text = "PV")) %>%  ## y축 labeling 
    hc_xAxis(title = list(text = "일자")) %>%  ## x축 labeling
    hc_plotOptions(series = list(marker = list(enabled = TRUE,symbol = "circle"))) %>%
    hc_tooltip(crosshairs = TRUE,
               shared = TRUE,
               borderColor = "black",
               pointFormat = '<span style="color:{point.color}"> \u25CF </span> {point.promo_type}: {point.value:,.0f} <br>') %>%  ## tooltip 설정
    hc_title(text = "<b> 프로모션 uv비교</b>",
             margin = 20, align = "center",
             style = list(color = "#000000", useHTML = TRUE))
  

```



## 쇼핑몰별 상품별 매출{.tabset .tabset-fade .tabset-pills}


### 더제이수 매출(Z결제 vs 자사몰)

```{r, echo=FALSE}
dat = orders.thejsoo
#dat = dat %>%
#  filter(date_paid_simple >= start_date & date_paid_simple <= end_date) 

dat = dat %>% filter(shop_name == '더제이수')

hcoptslang <- getOption("highcharter.lang")
  hcoptslang$thousandsSep <- ","
  options(highcharter.lang = hcoptslang)
  
hchart(dat, "column", hcaes(x=date_paid_simple,y=order_amount, group = type, colour = type))%>%
    hc_yAxis(title = list(text = "매출액")) %>%  ## y축 labeling 
    hc_xAxis(title = list(text = "일자")) %>%  ## x축 labeling
    hc_plotOptions(series = list(marker = list(enabled = TRUE,symbol = "circle"))) %>%
    hc_tooltip(crosshairs = TRUE,
               shared = TRUE,
               borderColor = "black",
               pointFormat = '<span style="color:{point.color}"> \u25CF </span> {point.type}: {point.order_amount:,.0f} <br>') %>%  ## tooltip 설정
    hc_title(text = "<b>  쇼핑몰 일별 매출(더제이수)</b>",
             margin = 20, align = "center",
             style = list(color = "#000000", useHTML = TRUE))%>%
  hc_plotOptions(column = list(
   dataLabels = list(enabled = FALSE),
   stacking = "normal",
   enableMouseTracking = TRUE)
   ) %>%
  hc_add_series(
              data = dat %>% group_by(date_paid_simple) %>% summarise(total = sum(order_amount)) %>% mutate(type = '전체'),
              mapping = hcaes(x = date_paid_simple, y = total,group=type),
              type = "line",
              color = "red",
              yAxis = 0,
              tooltip = list(pointFormat = '<span style="color:{point.color}"> \u25CF </span> 전체매출 : {point.total:,.0f}')
    )  %>%
  hc_xAxis(plotBands = list(
      list(label = list(text = "기획전"), 
            from =  datetime_to_timestamp(as.Date(start_date)), 
             to = datetime_to_timestamp(as.Date(end_date)), 
            color = "rgba(255,60,0, 0.4)")
    ))
```

### 더제이수 매출(비율, Z결제 vs 자사몰)

```{r, echo=FALSE}
dat = orders.thejsoo
#dat = dat %>%
#  filter(date_paid_simple >= start_date & date_paid_simple <= end_date) 

dat = dat %>% filter(shop_name == '더제이수')

hcoptslang <- getOption("highcharter.lang")
  hcoptslang$thousandsSep <- ","
  options(highcharter.lang = hcoptslang)
  
hchart(dat, "column", hcaes(x=date_paid_simple,y=order_amount, group = type, colour = type))%>%
    hc_yAxis(title = list(text = "비율")) %>%  ## y축 labeling 
    hc_xAxis(title = list(text = "일자")) %>%  ## x축 labeling
    #hc_plotOptions(series = list(marker = list(enabled = TRUE,symbol = "circle"))) %>%
    hc_plotOptions(column = list(
                                dataLabels = list(enabled = FALSE),
                                stacking = "percent",
                                enableMouseTracking = TRUE)
                    ) %>%
    hc_tooltip(crosshairs = TRUE,
               shared = TRUE,
               borderColor = "black",
               pointFormat = '<span style="color:{point.color}"> \u25CF </span> {point.type}: {point.percentage:.1f} % <br>') %>%  ## tooltip 설정
    hc_title(text = "<b>  쇼핑몰 일별 매출(더제이수)</b>",
             margin = 20, align = "center",
             style = list(color = "#000000", useHTML = TRUE)) %>%
  hc_xAxis(plotBands = list(
      list(label = list(text = "기획전",y=2), 
            from =  datetime_to_timestamp(as.Date(start_date)), 
             to = datetime_to_timestamp(as.Date(end_date)), 
            color = "rgba(255,60,0, 0.4)")
    ))
```



### 주문액

```{r, echo=FALSE}
dat = orders.thejsoo %>%
  #filter(date_paid_simple>=start_date & date_paid_simple <= end_date) %>%
  group_by(shop_id, shop_name, date_paid_simple) %>%
  summarise(order_num = sum(order_num),
            order_amount = sum(order_amount),
            paid_user_num = sum(paid_user_num))


hcoptslang <- getOption("highcharter.lang")
  hcoptslang$thousandsSep <- ","
  options(highcharter.lang = hcoptslang)
  
hchart(dat, "line", hcaes(x = date_paid_simple, y = order_amount, group = shop_name, colour = shop_name))%>%
    hc_yAxis(title = list(text = "주문액")) %>%  ## y축 labeling 
    hc_xAxis(title = list(text = "일자")) %>%  ## x축 labeling
    hc_plotOptions(series = list(marker = list(enabled = TRUE,symbol = "circle"))) %>%
    hc_tooltip(crosshairs = TRUE,
               shared = TRUE,
               borderColor = "black",
               pointFormat = '<span style="color:{point.color}"> \u25CF </span> {point.shop_name}: {point.order_amount:,.0f} <br>') %>%  ## tooltip 설정
    hc_title(text = "<b> 주문액 </b>",
             margin = 20, align = "center",
             style = list(color = "#000000", useHTML = TRUE))%>%
  hc_xAxis(plotBands = list(
      list(label = list(text = "기획전"), 
            from =  datetime_to_timestamp(as.Date(start_date)), 
             to = datetime_to_timestamp(as.Date(end_date)), 
            color = "rgba(255,60,0, 0.4)")
    ))
```

### 주문수


```{r, echo=FALSE}
dat = orders.thejsoo %>%
  #filter(date_paid_simple>=start_date & date_paid_simple <= end_date)  %>%
  group_by(shop_id, shop_name, date_paid_simple) %>%
  summarise(order_num = sum(order_num),
            order_amount = sum(order_amount),
            paid_user_num = sum(paid_user_num))


hcoptslang <- getOption("highcharter.lang")
  hcoptslang$thousandsSep <- ","
  options(highcharter.lang = hcoptslang)
  
hchart(dat, "line", hcaes(x = date_paid_simple, y = order_num, group = shop_name, colour = shop_name))%>%
    hc_yAxis(title = list(text = "주문수")) %>%  ## y축 labeling 
    hc_xAxis(title = list(text = "일자")) %>%  ## x축 labeling
    hc_plotOptions(series = list(marker = list(enabled = TRUE,symbol = "circle"))) %>%
    hc_tooltip(crosshairs = TRUE,
               shared = TRUE,
               borderColor = "black",
               pointFormat = '<span style="color:{point.color}"> \u25CF </span> {point.shop_name}: {point.order_num:,.0f} <br>') %>%  ## tooltip 설정
    hc_title(text = "<b> 주문수 </b>",
             margin = 20, align = "center",
             style = list(color = "#000000", useHTML = TRUE))%>%
  hc_xAxis(plotBands = list(
      list(label = list(text = "기획전"), 
            from =  datetime_to_timestamp(as.Date(start_date)), 
             to = datetime_to_timestamp(as.Date(end_date)), 
            color = "rgba(255,60,0, 0.4)")
    ))
```



### 객단가


```{r, echo=FALSE}
dat = orders.thejsoo %>%
  #filter(date_paid_simple>=start_date & date_paid_simple <= end_date)  %>%
  group_by(shop_id, shop_name, date_paid_simple) %>%
  summarise(order_num = sum(order_num),
            order_amount = sum(order_amount),
            paid_user_num = sum(paid_user_num))
dat$ct = round(dat$order_amount / dat$paid_user_num)

hcoptslang <- getOption("highcharter.lang")
  hcoptslang$thousandsSep <- ","
  options(highcharter.lang = hcoptslang)
  
hchart(dat, "line", hcaes(x = date_paid_simple, y = ct, group = shop_name, colour = shop_name))%>%
    hc_yAxis(title = list(text = "객단가")) %>%  ## y축 labeling 
    hc_xAxis(title = list(text = "일자")) %>%  ## x축 labeling
    hc_plotOptions(series = list(marker = list(enabled = TRUE,symbol = "circle"))) %>%
    hc_tooltip(crosshairs = TRUE,
               shared = TRUE,
               borderColor = "black",
               pointFormat = '<span style="color:{point.color}"> \u25CF </span> {point.shop_name}: {point.ct:,.0f} <br>') %>%  ## tooltip 설정
    hc_title(text = "<b> 객단가 </b>",
             margin = 20, align = "center",
             style = list(color = "#000000", useHTML = TRUE))%>%
  hc_xAxis(plotBands = list(
      list(label = list(text = "기획전"), 
            from =  datetime_to_timestamp(as.Date(start_date)), 
             to = datetime_to_timestamp(as.Date(end_date)), 
            color = "rgba(255,60,0, 0.4)")
    ))
```


### 즐겨찾기 변화


```{r, echo=FALSE}
dat = shop_dailies_thejsoo

hcoptslang <- getOption("highcharter.lang")
  hcoptslang$thousandsSep <- ","
  options(highcharter.lang = hcoptslang)

  
  
#custom_dashes =  rep(c("Solid","Solid","Solid","Solid","Solid","ShortDashDotDot"),times = 28)

hchart(dat, "line", hcaes(x = as.Date(date_simple)
                            , y = bookmark_change_amount
                            , group = shop_name
                            , colour = shop_name))%>%
                            #,dashStyle = custom_dashes)
    hc_yAxis(title = list(text = "즐겨찾기 수")) %>%  ## y축 labeling 
    hc_xAxis(title = list(text = "일자")) %>%  ## x축 labeling
    hc_plotOptions(series = list(marker = list(enabled = TRUE,symbol = "circle"))) %>%
    hc_tooltip(crosshairs = TRUE,
               shared = TRUE,
               borderColor = "black",
               pointFormat = '<span style="color:{point.color}"> \u25CF </span> {point.shop_name}: {point.bookmark_change_amount:,.0f} <br>') %>%  ## tooltip 설정
    hc_title(text = "<b> 즐겨찾기 수 </b>",
             margin = 20, align = "center",
             style = list(color = "#000000", useHTML = TRUE)) %>%
  hc_xAxis(plotBands = list(
      list(from =  datetime_to_timestamp(as.Date(start_date))
           , to = datetime_to_timestamp(as.Date(end_date))
           , color = "rgba(255,60,0, 0.4)")
    ))%>%
  hc_xAxis(plotBands = list(
      list(label = list(text = "기획전"), 
            from =  datetime_to_timestamp(as.Date(start_date)), 
             to = datetime_to_timestamp(as.Date(end_date)), 
            color = "rgba(255,60,0, 0.4)")
    ))
```


### 찜 변화



```{r, echo=FALSE}
dat = shop_dailies_thejsoo

hcoptslang <- getOption("highcharter.lang")
  hcoptslang$thousandsSep <- ","
  options(highcharter.lang = hcoptslang)
  
hchart(dat, "line", hcaes(x = as.Date(date_simple), y = my_goods_count_change, group = shop_name, colour = shop_name))%>%
    hc_yAxis(title = list(text = "찜 수")) %>%  ## y축 labeling 
    hc_xAxis(title = list(text = "일자")) %>%  ## x축 labeling
    hc_plotOptions(series = list(marker = list(enabled = TRUE,symbol = "circle"))) %>%
    hc_tooltip(crosshairs = TRUE,
               shared = TRUE,
               borderColor = "black",
               pointFormat = '<span style="color:{point.color}"> \u25CF </span> {point.shop_name}: {point.my_goods_count_change:,.0f} <br>') %>%  ## tooltip 설정
    hc_title(text = "<b> 찜 수 </b>",
             margin = 20, align = "center",
             style = list(color = "#000000", useHTML = TRUE)) %>%
  hc_xAxis(plotBands = list(
      list(from =  datetime_to_timestamp(as.Date(start_date))
           , to = datetime_to_timestamp(as.Date(end_date))
           , color = "rgba(255,60,0, 0.4)")
    ))%>%
  hc_xAxis(plotBands = list(
      list(label = list(text = "기획전"), 
            from =  datetime_to_timestamp(as.Date(start_date)), 
             to = datetime_to_timestamp(as.Date(end_date)), 
            color = "rgba(255,60,0, 0.4)")
    ))
```



